<a href="https://colab.research.google.com/github/senemcet/automlcourse/blob/main/061225.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#onehot-label-ordinal encoder ornekleri
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [ ]:
veri = np.array([
    ['Kırmızı', 'Küçük', 'Lise'],
    ['Mavi', 'Orta', 'İlkokul'],
    ['Yeşil', 'Büyük', 'Üniversite'],
    ['Kırmızı', 'Küçük', 'Lise']
])


In [ ]:
# OneHotEncoder örneği (renkler için ayrı sütunlar açıyoruz)
onehot_encoder = OneHotEncoder(sparse_output=False)
renk_encoded = onehot_encoder.fit_transform(veri[:, 0].reshape(-1, 1))

In [ ]:
# LabelEncoder örneği ( sıralama)
label_encoder = LabelEncoder()
boyut_encoded = label_encoder.fit_transform(veri[:, 1])

In [ ]:
# OrdinalEncoder örneği (kendi içinde hiyerarşisi olacak şekilde sıralı şekilde sıralıyoruz)
ordinal_encoder = OrdinalEncoder(categories=[['İlkokul', 'Lise', 'Üniversite']])
egitim_encoded = ordinal_encoder.fit_transform(veri[:, 2].reshape(-1, 1))

In [ ]:
# Sonuçları birleştirme
sonuc = np.hstack((renk_encoded, boyut_encoded.reshape(-1, 1), egitim_encoded))

In [ ]:
# Orijinal verileri ve dönüştürülmüş verileri yazdırma
print("Orijinal Veri:\n", veri)
print("\nDönüştürülmüş Veri:\n", sonuc)

Orijinal Veri:
 [['Kırmızı' 'Küçük' 'Lise']
 ['Mavi' 'Orta' 'İlkokul']
 ['Yeşil' 'Büyük' 'Üniversite']
 ['Kırmızı' 'Küçük' 'Lise']]

Dönüştürülmüş Veri:
 [[1. 0. 0. 1. 1.]
 [0. 1. 0. 2. 0.]
 [0. 0. 1. 0. 2.]
 [1. 0. 0. 1. 1.]]


In [ ]:
# Her encoder’ın kategorilerini ve dönüştürülmüş değerlerini yazdırma
print("\nOneHotEncoder Kategorileri:\n", onehot_encoder.categories_)
print("\nLabelEncoder Kategorileri:\n", label_encoder.classes_)
print("\nOrdinalEncoder Kategorileri:\n", ordinal_encoder.categories_)


OneHotEncoder Kategorileri:
 [array(['Kırmızı', 'Mavi', 'Yeşil'], dtype='<U10')]

LabelEncoder Kategorileri:
 ['Büyük' 'Küçük' 'Orta']

OrdinalEncoder Kategorileri:
 [array(['İlkokul', 'Lise', 'Üniversite'], dtype=object)]
